<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>10.0</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <VersionPrefix>1.0.0</VersionPrefix>
    <Authors>zahidtechy</Authors>
    <Company>Datavanced</Company>
    <Copyright>Copyright (c) zahidtechy</Copyright>
    <RepositoryUrl>https://github.com/zahidtechy/Stedi</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/zahidtechy/Stedi</PackageProjectUrl>
  </PropertyGroup>
</Project>
