name: nuget-publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"
      - name: Restore
        run: dotnet restore Stedi.Healthcare.sln
      - name: Build
        run: dotnet build Stedi.Healthcare.sln -c Release --no-restore
      - name: Pack
        run: dotnet pack src/Stedi.Healthcare/Stedi.Healthcare.csproj -c Release --no-build --no-restore -o artifacts
      - name: Push to GitHub Packages
        run: |
          dotnet nuget push artifacts/*.nupkg \
            --api-key "${{ secrets.GITHUB_TOKEN }}" \
            --source "https://nuget.pkg.github.com/zahidtechy/index.json" \
            --skip-duplicate
      - name: NuGet login (OIDC)
        uses: NuGet/login@v1
        id: login
        with:
          user: zahid94
      - name: Push to nuget.org
        run: |
          dotnet nuget push artifacts/*.nupkg \
            --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
